# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

strategy:
    maxParallel: 3
    matrix: 
       win:
          image: 'windows-latest'
          jdkVersion: '1.7'
       macos:
          image: 'macos-latest'
          jdkVersion: '1.8'
       linux: 
          image: 'ubuntu-latest'
          jdkVersion: '1.7' 
pool:
  vmImage: $(image)

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
